apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balancer-public
  namespace: load-balancer
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["balancer.example.com"]
      secretName: balancer-public-tls
  rules:
    - host: balancer.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: balancer-public, port: { name: http } }
