apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: balancer
  namespace: load-balancer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: management
  endpoints:
    - port: management
      path: /metrics
      interval: 15s
      authorization:
        type: Bearer
        credentials:
          name: balancer-secrets
          key: admin-token
