apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
configMapGenerator:
  - name: balancer-migration-config
    namespace: load-balancer
    files:
      - config.yaml=config.yaml
generatorOptions:
  disableNameSuffixHash: false
images:
  - name: ghcr.io/owner/cloud-test-assignment-balancer
    newName: ghcr.io/OWNER/REPOSITORY-balancer
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
