apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - rbac.yaml
  - controller.yaml
patches:
  - path: balancer-service-account-patch.yaml
configMapGenerator:
  - name: balancer-config
    namespace: load-balancer
    behavior: replace
    files:
      - config.yaml=config.yaml
images:
  - name: ghcr.io/owner/cloud-test-assignment-balancer
    newName: ghcr.io/OWNER/REPOSITORY-balancer
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
