apiVersion: v1
kind: ServiceAccount
metadata:
  name: balancer-discovery
  namespace: load-balancer
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: balancer-endpointslice-reader
  namespace: application
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: balancer-endpointslice-reader
  namespace: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: balancer-endpointslice-reader
subjects:
  - kind: ServiceAccount
    name: balancer-discovery
    namespace: load-balancer
